---

- file:
    path: /etc/NetworkManager/conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: 90-dns-none.conf
  copy:
    src:  90-dns-none.conf
    dest: /etc/NetworkManager/conf.d
    owner: root
    group: root
    mode: 0755

- name: resolv.conf
  copy:
    src: resolv.conf
    dest: /etc
    owner: root
    group: root
    mode: 0600

- name: Set defaultNIC local fact
  template:
    src: defaultNIC.fact.j2
    dest: /etc/ansible/facts.d/defaultNIC.fact
    owner: root
    group: root
    mode: 0755

- name: refresh facts
  setup:

- block:
  - name: Remove DNS entries in default ifcfg file
     become: yes
     lineinfile:
       path: /etc/sysconfig/network-scripts/ifcfg-{{ defaultNIC }}
       regexp: "DNS"
       state: absent
       backup: yes
     check_mode: yes
  
  - name: Remove DOMAIN entries in default ifcfg file
     become: yes
     lineinfile:
       path: /etc/sysconfig/network-scripts/ifcfg-{{ defaultNIC }}
       regexp: "DOMAIN"
       state: absent
       backup: yes
     check_mode: yes
  
  - name: Ensure NM_CONTROLLED is enabled
     become: yes
     lineinfile:
       path: /etc/sysconfig/network-scripts/ifcfg-{{ defaultNIC }}
       regexp: "NM_CONTROLLED="
       line: "NM_CONTROLLED=YES"
       state: present
       backup: yes
     check_mode: yes

  notify:
   - restart NetworkManager

#
