---

- file:
    path: /etc/NetworkManager/conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- block: 
   - name: 90-dns-none.conf
     copy:
       src:  90-dns-none.conf
       dest: /etc/NetworkManager/conf.d
       owner: root
       group: root
       mode: 0755

   - name: resolv.conf
     copy:
       src: resolv.conf
       dest: /etc
       owner: root
       group: root
       mode: 0600
  notify:
   - restart NetworkManager
#
# Run script to remove DNS, DOMAIN, NM_controlled from ifcfg of default NIC
#
#
